aws:
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  region: "<%= ENV['AWS_REGION'] %>"
twitter:
  id: "<%= ENV['TWITTER_NAME'] %>"
  url: "<%= ENV['TWITTER_URL'] %>"
question: "<%= ENV['QUESTION'] %>"
