aws:
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  region: "<%= ENV['AWS_REGION'] %>"
twitter:
  id: "<%= ENV['TWITTER_NAME'] %>"
  url: "<%= ENV['TWITTER_URL'] %>"
  api_key: "<%= ENV['TWITTER_API_KEY']%>"
  api_secret_key: "<%= ENV['TWITTER_API_SECRET_KEY']%>"
  access_token: "<%= ENV['TWITTER_ACCESS_TOKEN']%>"
  access_token_secret: "<%= ENV['TWITTER_ACCESS_TOKEN_SECRET']%>"
question: "<%= ENV['QUESTION'] %>"
url: "http://pri-image-db.site/"
prism_db_api_episode_url: 'https://prismdb.takanakahiko.me/api/episode/'
